// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./message.proto
package com.example.glowybits.rcp;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

public final class RpcMessage extends Message {

  @ProtoField(tag = 1)
  public final ChangeSettings settings;

  @ProtoField(tag = 2)
  public final Status status;

  private RpcMessage(Builder builder) {
    super(builder);
    this.settings = builder.settings;
    this.status = builder.status;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RpcMessage)) return false;
    RpcMessage o = (RpcMessage) other;
    return equals(settings, o.settings)
        && equals(status, o.status);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = settings != null ? settings.hashCode() : 0;
      result = result * 37 + (status != null ? status.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RpcMessage> {

    public ChangeSettings settings;
    public Status status;

    public Builder() {
    }

    public Builder(RpcMessage message) {
      super(message);
      if (message == null) return;
      this.settings = message.settings;
      this.status = message.status;
    }

    public Builder settings(ChangeSettings settings) {
      this.settings = settings;
      return this;
    }

    public Builder status(Status status) {
      this.status = status;
      return this;
    }

    @Override
    public RpcMessage build() {
      return new RpcMessage(this);
    }
  }
}
