// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./message.proto
package com.example.glowybits.rcp;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoEnum;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.ENUM;
import static com.squareup.wire.Message.Datatype.INT32;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class RpcMessage extends Message {

  public static final Action DEFAULT_ACTION = Action.FRAMES_PER_SECOND;
  public static final Integer DEFAULT_ARG1 = 0;

  @ProtoField(tag = 1, type = ENUM, label = REQUIRED)
  public final Action action;

  @ProtoField(tag = 2, type = INT32)
  public final Integer arg1;

  private RpcMessage(Builder builder) {
    super(builder);
    this.action = builder.action;
    this.arg1 = builder.arg1;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof RpcMessage)) return false;
    RpcMessage o = (RpcMessage) other;
    return equals(action, o.action)
        && equals(arg1, o.arg1);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    if (result == 0) {
      result = action != null ? action.hashCode() : 0;
      result = result * 37 + (arg1 != null ? arg1.hashCode() : 0);
      hashCode = result;
    }
    return result;
  }

  public static final class Builder extends Message.Builder<RpcMessage> {

    public Action action;
    public Integer arg1;

    public Builder() {
    }

    public Builder(RpcMessage message) {
      super(message);
      if (message == null) return;
      this.action = message.action;
      this.arg1 = message.arg1;
    }

    public Builder action(Action action) {
      this.action = action;
      return this;
    }

    public Builder arg1(Integer arg1) {
      this.arg1 = arg1;
      return this;
    }

    @Override
    public RpcMessage build() {
      checkRequiredFields();
      return new RpcMessage(this);
    }
  }

  public enum Action {
    @ProtoEnum(0)
    FRAMES_PER_SECOND,
    @ProtoEnum(1)
    CHANGE_MODE,
  }
}
