// Code generated by Wire protocol buffer compiler, do not edit.
// Source file: ./message.proto
package com.example.glowybits.rcp;

import com.squareup.wire.Message;
import com.squareup.wire.ProtoField;

import static com.squareup.wire.Message.Datatype.UINT32;
import static com.squareup.wire.Message.Label.REQUIRED;

public final class Status extends Message {

  public static final Integer DEFAULT_FPS = 0;

  @ProtoField(tag = 1, type = UINT32, label = REQUIRED)
  public final Integer fps;

  private Status(Builder builder) {
    super(builder);
    this.fps = builder.fps;
  }

  @Override
  public boolean equals(Object other) {
    if (other == this) return true;
    if (!(other instanceof Status)) return false;
    return equals(fps, ((Status) other).fps);
  }

  @Override
  public int hashCode() {
    int result = hashCode;
    return result != 0 ? result : (hashCode = fps != null ? fps.hashCode() : 0);
  }

  public static final class Builder extends Message.Builder<Status> {

    public Integer fps;

    public Builder() {
    }

    public Builder(Status message) {
      super(message);
      if (message == null) return;
      this.fps = message.fps;
    }

    public Builder fps(Integer fps) {
      this.fps = fps;
      return this;
    }

    @Override
    public Status build() {
      checkRequiredFields();
      return new Status(this);
    }
  }
}
